version: '3'
services:
  turnero:
    build:
      context: .
      dockerfile: Dockerfile  # Path to your Spring Boot app's Dockerfile
    ports:
      - '8088:8080'
    environment:
       SPRING_DATA_MONGODB_URI: mongodb://localhost:27017/turnero
#      SPRING_DATA_MONGODB_HOST: host.docker.internal
#      SPRING_DATA_MONGODB_PORT: 27017
#      SPRING_DATA_MONGODB_DATABASE: 'turnero'
#      SPRING_DATA_MONGODB_USERNAME: null
